name: Build Java

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "admin/**"
      - "core/**"

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Setup Gradle & Cache Gradle packages
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build with Gradle
        run: ./gradlew api:build