name: Pull Request Test
run-name: Pull Request Test :${{ github.run_number }}
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  Test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17 - temurin
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle & Cache Gradle packages
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Test And Build
        run: |
          if [[ $(git diff --name-only HEAD^ HEAD) =~ ^admin/ ]]; then
            ./gradlew admin:clean admin:test admin:build
          fi
          if [[ $(git diff --name-only HEAD^ HEAD) =~ ^api/ ]]; then
            ./gradlew api:clean api:test api:build
          fi
